### ISSUE TITLE
Release 0.5.1

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab-contrib/jupyter-videochat#23]
- [x] bump versions
- [x] validate on binder
- [x] update docs
  - [ ] screenshot
  - [x] badges
  - [x] changelog
- [x] tag
- [x] upload
  - [x] pypi
  - [x] npm
- [ ] postmortem
  - [ ] bump version
  - [x] validate on binder [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/bollwyvl/34a3356e4e3f85ed8bceee917e00a852/HEAD?urlpath=lab)
  - [x] merge conda-forge bot PR 
  - [ ] update CONTRIBUTING with lessons learned

**Comment by fcollonval** [comment]
Closing this as 0.5.1 was released
