### ISSUE TITLE
Move to jupyterlab-contrib?

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab-contrib/jupyter-videochat#34]
I haven't had any time to do anything with this extension for a while now, and it looks like I won't for a while. I'd like to move this extension to the [jupyterlab-contrib](https://jupyterlab-contrib.github.io/) organization. 

Pinging @jptio, who I think is part of the org admins for jupyterlab-contrib? Also @bollwyvl who has been doing most of the recent work in this repo.

Part of my [Volunteer Amnesty](https://www.volunteeramnestyday.net/) :)

**Comment by yuvipanda** [comment]
Would probably involve moving https://github.com/yuvipanda/jupyter-videochat-demo as well

**Comment by bollwyvl** [comment]
The demo could be rolled into a branch...

**Comment by yuvipanda** [comment]
Opened https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/15 to do the transfer.

**Comment by fcollonval** [comment]
Thanks for transferring Yuvi - I got everything set on pypi and npm.

The two remaining tasks are:
- [ ] Update links
- [ ] Move binder demo in a branch

I'll do those tasks.

**Comment by fcollonval** [comment]
Let's close this. Thanks again for pushing it through.

**Comment by yuvipanda** [comment]
Thank you very much, @fcollonval!
