### ISSUE TITLE
Quick access to creating a seperate browser tab which only comprises of the video chat

### ISSUE THREAD

**Issue by honno** [jupyterlab-contrib/jupyter-videochat#44]
Was using this nifty tool for the first time thanks to @tonyfast and folks inside a RTC Jupyter Labs session. As someone who's not familiar with Jupyter stuff outside of basic IPython cells, the experience was a bit *too* fun in that I found it hard to contextualise everything else going on in the Labs environment.

 I'm sure I could of played around with the current sidebar feature and stuff but maybe there is room to improve that first-time user experience somehow. For example, if there was a button somewhere that would create a new tab that was just the video chat ala Google Meet.... just a first thought!

**Comment by bollwyvl** [comment]
Thanks for the interest.

Opening in another tab introduces a number of challenges from a future API integration point of view (e.g. #5, #24), but is probably feasible... but would not be my first choice as a default, however FANGMA does it. The ability to _look at someone while doing something else_ is one of the features of having it in lab in the first place. _Someone_ who's throwing you into a Lab session _and_ piling Jitsi on top of it is being rather cavalier with your attention.

Under the hood, the thing's just an iframe, which _should_ be openable as a new tab via right click... though Jitsi may have overloaded it (much like lab itself does) requiring a <kbd>Ctrl+Shift+Click</kbd> to get at it.

**Comment by bollwyvl** [comment]
The user story this might jive with is _I'm using Jupyter for the first time with `retrolab`_: in some (accidental) tests, we found that it _pretty much works_ without any special case, though it's:
- non-obvious how to get to it
- got some CSS issues (the chat is about 200px tall)

**Comment by bollwyvl** [comment]
Without _too_ much jiggery-pokery, this looks okay:

| what | it looks like |
|-|-|
| add a _New Video Chat_ button | ![Screenshot from 2021-07-25 16-26-48](https://user-images.githubusercontent.com/45380/126912508-091a303b-e13c-4529-afb6-de6e56517d03.png)
| the pre-lobby | ![Screenshot from 2021-07-25 16-25-13](https://user-images.githubusercontent.com/45380/126912459-ea34f671-dd4b-4470-8ddd-135b62808fb5.png)
| in the chat | ![Screenshot from 2021-07-25 16-24-49](https://user-images.githubusercontent.com/45380/126912432-4e74790f-43e0-4057-85a3-ba83823b9c05.png)
| in zen mode | ![Screenshot from 2021-07-25 16-28-29](https://user-images.githubusercontent.com/45380/126912559-04e7a57a-6fb0-47c1-9d96-0d7d770abf3b.png)

**Comment by bollwyvl** [comment]
Mostly working... #41 has a static one that you can try out right now:

https://jupyter-videochat--41.org.readthedocs.build/en/41/_static/lite/retro/tree/

**Comment by bollwyvl** [comment]
Fixed in [`v0.6.0`](https://github.com/jupyterlab-contrib/jupyter-videochat/releases/tag/v0.6.0).
