### ISSUE TITLE
add a note in docs how to launch a video meetings

### ISSUE THREAD

**Issue by raybellwaves** [jupyterlab-contrib/jupyter-videochat#50]
Can across this today.

I'll confess. It took me a while to work out what to do next beyond installing it.

From looking at the snapshot I see it can be found in the Launcher section (i.e. click + (New Launcher)

https://user-images.githubusercontent.com/45380/106391412-312d0400-63bb-11eb-9ed9-af3c4fe85ee4.png

It would be worth adding a note here above configuration in a section called "Launch"

https://jupyter-videochat.readthedocs.io/en/latest/user-guide.html#configuration

**Comment by bollwyvl** [comment]
Updated in #62, thanks again!
