### ISSUE TITLE
Microphone and camera access on jhub

### ISSUE THREAD

**Issue by raybellwaves** [jupyterlab-contrib/jupyter-videochat#52]
Using the-littest-jupyterhub (per https://github.com/raybellwaves/tljh-plugin/blob/main/tljh_plugin.py#L38) and trying to get this extension working. Can't work out how give permission to camera and mic

<img width="374" alt="Screen Shot 2022-01-03 at 3 15 11 PM" src="https://user-images.githubusercontent.com/17162724/147975893-072f4829-d42f-4e4f-9af3-5ca4a3d45db0.png">

**Comment by bollwyvl** [comment]
Once you've gotten to the iframe loading, you've left what this extension controls, and might have to take a look at the jitsi [docs](https://jitsi.github.io/handbook/) or [forum](https://community.jitsi.org/).

My guess: it's likely your browser has a toolbar button that might tell you how to fix it, your mileage may vary but... 

| browser | image |
|-|-|
| firefox asks to the left of the url | ![Screenshot from 2022-04-03 18-59-49](https://user-images.githubusercontent.com/45380/161454768-044885d0-27c1-410e-80cc-f597848e1845.png) |
| chromium asks there, then moves the icon to the right | ![Screenshot from 2022-04-03 19-01-25](https://user-images.githubusercontent.com/45380/161454836-ab3c753c-20f1-4b95-8462-c3a03466604a.png) ![chromium2](https://user-images.githubusercontent.com/45380/161454942-e04c4609-a56e-44b9-9348-b14f21081b7f.png)
|
